<section class="admin__page-section" id="delivery-date-content">
    <div class="admin__page-section-title">
        <span class="title"><?= $block->escapeHtml(__('Delivery Date Information')) ?></span>
    </div>
    <div class="admin__page-section-content">
        <div id="delivery-date">
            <strong><?= $block->escapeHtml(__('Delivery Date')); ?></strong>
            <span><?= $block->escapeHtml($block->getDeliveryDate()) ?></span>
        </div>
        <div id="delivery-comment">
            <strong><?= $block->escapeHtml(__('Comment')); ?>:</strong>
            <br/>
            <?= $block->escapeHtml($block->getDeliveryComment()) ?>
        </div>
    </div>
</section>
<script type="text/javascript">
    require(
        ['jquery'],
        function($) {
            $('#delivery-date-content').insertAfter($('.order-view-billing-shipping'));
        }
    );
</script>
