<div id="delivery-date">
    <strong><?= $block->escapeHtml(__('Delivery Date')); ?></strong>
    <span class="price"><?= $block->escapeHtml($block->getDeliveryDate()); ?></span>
</div>
<div id="delivery-comment">
    <strong><?= $block->escapeHtml(__('Comment')); ?>:</strong>
    <br/>
    <span class="price"><?= $block->escapeHtml($block->getDeliveryComment()); ?></span>
</div>
<script type="text/javascript">
    require(
        ['jquery'],
        function($) {
            var element = $('#delivery-date').detach();
            $('.box-order-shipping-method').append(element);
            var element = $('#delivery-comment').detach();
            $('.box-order-shipping-method').append(element);
        }
    );
</script>
